-- =====================================================================
-- 0200 · Organización: empresa, sucursales, cajas y almacenes (doc 05 §2.1)
-- =====================================================================

create table public.empresa (
  id_empresa             bigint generated by default as identity primary key,
  razon_social           varchar(150) not null,
  rtn                    char(14)     not null unique check (public.rtn_valido(rtn)),
  nombre_comercial       varchar(120),
  domicilio_casa_matriz  varchar(250),
  moneda                 char(3)      not null default 'HNL',
  creado                 timestamptz  not null default now()
);

create table public.sucursal (
  id_sucursal  bigint generated by default as identity primary key,
  id_empresa   bigint       not null references public.empresa,
  codigo       varchar(10)  not null unique,
  nombre       varchar(80)  not null,
  direccion    varchar(250),
  telefono     varchar(20),
  activa       boolean      not null default true
);

create table public.caja (
  id_caja          bigint generated by default as identity primary key,
  id_sucursal      bigint        not null references public.sucursal,
  codigo           varchar(10)   not null unique,          -- C03
  serie_folio      varchar(5)    not null,                 -- prefijo de folios: C03-000482
  id_dispositivo   varchar(60)   unique,                   -- X-Dispositivo-Id
  limite_efectivo  numeric(12,2) not null default 5000 check (limite_efectivo >= 0),  -- RN-07
  activa           boolean       not null default true
);
create index caja_sucursal_idx on public.caja (id_sucursal);

create table public.almacen (
  id_almacen   bigint generated by default as identity primary key,
  id_sucursal  bigint      not null references public.sucursal,
  nombre       varchar(60) not null,
  tipo         varchar(10) not null check (tipo in ('PISO', 'BODEGA', 'MERMA')),
  unique (id_sucursal, nombre)
);
create index almacen_sucursal_idx on public.almacen (id_sucursal);

comment on table public.almacen is 'Cada sucursal tiene piso de venta, bodega y área de merma. La existencia se lleva por almacén.';
