-- =====================================================================
-- 1000 · Reglas y centro de alarmas de inventario (doc 12 §4–5)
-- Las alarmas de existencia se evalúan en la misma transacción que el
-- movimiento de inventario; las de caducidad, cada noche con pg_cron.
-- =====================================================================

create table public.regla_alarma (
  id_regla              bigint generated by default as identity primary key,
  tipo                  varchar(14)   not null check (tipo in (
                          'SIN_EXISTENCIA', 'NEGATIVA', 'CADUCADO', 'BAJO_MINIMO', 'REORDEN',
                          'POR_CADUCAR', 'MERMA_ALTA', 'DIF_CONTEO', 'SOBRE_MAXIMO', 'SIN_MOVIMIENTO')),
  alcance               varchar(10)   not null default 'GENERAL'
                        check (alcance in ('PRODUCTO', 'CATEGORIA', 'SUCURSAL', 'GENERAL')),
  id_alcance            bigint,
  umbral                numeric(12,3),
  dias                  int           check (dias >= 0),
  nivel                 varchar(11)   not null check (nivel in ('CRITICA', 'ADVERTENCIA', 'INFO')),
  id_rol_responsable    bigint        references public.rol,
  minutos_recordatorio  int           not null default 120 check (minutos_recordatorio > 0),
  activa                boolean       not null default true,
  check ((alcance = 'GENERAL') = (id_alcance is null))
);
create unique index regla_alarma_unica_idx
  on public.regla_alarma (tipo, alcance, coalesce(id_alcance, 0));

create table public.alarma (
  id_alarma     bigint generated by default as identity primary key,
  id_regla      bigint        not null references public.regla_alarma,
  tipo          varchar(14)   not null,
  id_producto   bigint        not null references public.producto,
  id_sucursal   bigint        not null references public.sucursal,
  id_lote       bigint        references public.lote,
  nivel         varchar(11)   not null,
  valor_actual  numeric(12,3),
  origen        varchar(16)   not null check (origen in ('POS', 'RECEPCION', 'AJUSTE', 'PROCESO_NOCTURNO', 'MOVIMIENTO')),
  estado        varchar(11)   not null default 'NUEVA' check (estado in ('NUEVA', 'VISTA', 'EN_ATENCION', 'RESUELTA')),
  id_asignado   bigint        references public.usuario,
  creada        timestamptz   not null default now(),
  actualizada   timestamptz   not null default now(),
  resuelta      timestamptz,
  check ((estado = 'RESUELTA') = (resuelta is not null))
);
-- RN-ALM-01: no se duplica una alarma abierta del mismo tipo, producto, sucursal y lote.
create unique index alarma_abierta_unica_idx
  on public.alarma (tipo, id_producto, id_sucursal, coalesce(id_lote, 0))
  where estado <> 'RESUELTA';
create index alarma_centro_idx on public.alarma (id_sucursal, estado, nivel);

create table public.alarma_historial (
  id_historial  bigint generated by default as identity primary key,
  id_alarma     bigint       not null references public.alarma on delete cascade,
  accion        varchar(20)  not null,
  comentario    varchar(500),
  id_usuario    bigint       references public.usuario,
  fecha         timestamptz  not null default now()
);
create index alarma_historial_alarma_idx on public.alarma_historial (id_alarma, fecha);

-- Regla más específica que aplica: PRODUCTO > CATEGORIA > SUCURSAL > GENERAL.
create or replace function public.regla_alarma_aplicable(p_tipo text, p_id_producto bigint, p_id_sucursal bigint)
returns public.regla_alarma
language sql
stable
set search_path = ''
as $$
  select r.*
  from public.regla_alarma r
  join public.producto p on p.id_producto = p_id_producto
  where r.tipo = p_tipo
    and r.activa
    and (   (r.alcance = 'PRODUCTO'  and r.id_alcance = p.id_producto)
         or (r.alcance = 'CATEGORIA' and r.id_alcance = p.id_categoria)
         or (r.alcance = 'SUCURSAL'  and r.id_alcance = p_id_sucursal)
         or  r.alcance = 'GENERAL')
  order by case r.alcance when 'PRODUCTO' then 1 when 'CATEGORIA' then 2 when 'SUCURSAL' then 3 else 4 end
  limit 1
$$;

-- Abre (o actualiza, RN-ALM-01) una alarma si se cumple la condición, y la
-- resuelve sola si dejó de cumplirse (RF-ALM-06). Guarda historial.
create or replace function public.sincronizar_alarma(
  p_tipo         text,
  p_id_producto  bigint,
  p_id_sucursal  bigint,
  p_id_lote      bigint,
  p_se_cumple    boolean,
  p_valor        numeric,
  p_origen       text
)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_regla   public.regla_alarma;
  v_alarma  public.alarma;
begin
  select * into v_alarma
  from public.alarma a
  where a.tipo = p_tipo and a.id_producto = p_id_producto and a.id_sucursal = p_id_sucursal
    and a.id_lote is not distinct from p_id_lote and a.estado <> 'RESUELTA'
  for update;

  if p_se_cumple then
    if v_alarma.id_alarma is not null then
      update public.alarma set valor_actual = p_valor, actualizada = now()
       where id_alarma = v_alarma.id_alarma;
      return;
    end if;

    v_regla := public.regla_alarma_aplicable(p_tipo, p_id_producto, p_id_sucursal);
    if v_regla.id_regla is null then
      return;                                   -- no hay regla activa: no se alarma
    end if;

    insert into public.alarma (id_regla, tipo, id_producto, id_sucursal, id_lote, nivel, valor_actual, origen)
    values (v_regla.id_regla, p_tipo, p_id_producto, p_id_sucursal, p_id_lote, v_regla.nivel, p_valor, p_origen)
    returning * into v_alarma;

    insert into public.alarma_historial (id_alarma, accion, comentario)
    values (v_alarma.id_alarma, 'CREADA', 'Valor: ' || coalesce(p_valor::text, '—'));

  elsif v_alarma.id_alarma is not null then
    update public.alarma
       set estado = 'RESUELTA', resuelta = now(), actualizada = now(), valor_actual = p_valor
     where id_alarma = v_alarma.id_alarma;

    insert into public.alarma_historial (id_alarma, accion, comentario)
    values (v_alarma.id_alarma, 'RESUELTA_AUTO', 'La condición dejó de cumplirse. Valor: ' || coalesce(p_valor::text, '—'));
  end if;
end;
$$;

-- Evalúa las alarmas de existencia de un producto en una sucursal.
create or replace function public.evaluar_alarmas_existencia(
  p_id_producto bigint,
  p_id_sucursal bigint,
  p_origen      text default 'MOVIMIENTO'
)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_exist  numeric(12,3);
  v_prod   public.producto;
  v_regla  public.regla_alarma;
begin
  select * into v_prod from public.producto where id_producto = p_id_producto;

  select coalesce(sum(e.cantidad), 0) into v_exist
  from public.existencia e
  join public.almacen a on a.id_almacen = e.id_almacen
  where e.id_producto = p_id_producto and a.id_sucursal = p_id_sucursal and a.tipo <> 'MERMA';

  perform public.sincronizar_alarma('NEGATIVA',       p_id_producto, p_id_sucursal, null, v_exist < 0,  v_exist, p_origen);
  perform public.sincronizar_alarma('SIN_EXISTENCIA', p_id_producto, p_id_sucursal, null, v_exist = 0,  v_exist, p_origen);
  perform public.sincronizar_alarma('BAJO_MINIMO',    p_id_producto, p_id_sucursal, null,
                                    v_exist > 0 and v_exist < v_prod.stock_minimo, v_exist, p_origen);

  -- Punto de reorden: el del producto o, si no tiene, el umbral de la regla.
  v_regla := public.regla_alarma_aplicable('REORDEN', p_id_producto, p_id_sucursal);
  perform public.sincronizar_alarma('REORDEN', p_id_producto, p_id_sucursal, null,
                                    v_exist > 0 and v_exist <= coalesce(v_prod.punto_reorden, v_regla.umbral, -1),
                                    v_exist, p_origen);

  perform public.sincronizar_alarma('SOBRE_MAXIMO', p_id_producto, p_id_sucursal, null,
                                    v_prod.stock_maximo is not null and v_exist > v_prod.stock_maximo, v_exist, p_origen);
end;
$$;

create or replace function public.tg_movimiento_alarmas()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  perform public.evaluar_alarmas_existencia(
    new.id_producto, new.id_sucursal,
    case new.tipo
      when 'VENTA'  then 'POS'
      when 'COMPRA' then 'RECEPCION'
      when 'AJUSTE' then 'AJUSTE'
      when 'MERMA'  then 'AJUSTE'
      else 'MOVIMIENTO'
    end);
  return null;
end;
$$;

create trigger movimiento_alarmas
  after insert on public.movimiento_inventario
  for each row execute function public.tg_movimiento_alarmas();

-- Proceso nocturno: lotes caducados (se bloquean, RN-EXI-03) y por caducar.
create or replace function public.evaluar_alarmas_caducidad(p_hoy date default current_date)
returns int
language plpgsql
security definer
set search_path = ''
as $$
declare
  r        record;
  v_dias   int;
  v_total  int := 0;
begin
  update public.lote set bloqueado = true
   where fecha_caducidad < p_hoy and not bloqueado;

  for r in
    select e.id_producto, a.id_sucursal, e.id_lote, l.fecha_caducidad, sum(e.cantidad) as cantidad
    from public.existencia e
    join public.almacen a on a.id_almacen = e.id_almacen and a.tipo <> 'MERMA'
    join public.lote l    on l.id_lote = e.id_lote
    where l.fecha_caducidad is not null
    group by e.id_producto, a.id_sucursal, e.id_lote, l.fecha_caducidad
  loop
    v_dias := coalesce((public.regla_alarma_aplicable('POR_CADUCAR', r.id_producto, r.id_sucursal)).dias, 7);

    perform public.sincronizar_alarma('CADUCADO', r.id_producto, r.id_sucursal, r.id_lote,
                                      r.cantidad > 0 and r.fecha_caducidad < p_hoy, r.cantidad, 'PROCESO_NOCTURNO');
    perform public.sincronizar_alarma('POR_CADUCAR', r.id_producto, r.id_sucursal, r.id_lote,
                                      r.cantidad > 0 and r.fecha_caducidad >= p_hoy
                                      and r.fecha_caducidad <= p_hoy + v_dias, r.cantidad, 'PROCESO_NOCTURNO');
    v_total := v_total + 1;
  end loop;

  return v_total;
end;
$$;

-- Cambio de estado manual desde el centro de alarmas (PUT /alarmas/{id}).
create or replace function public.atender_alarma(
  p_id_alarma   bigint,
  p_estado      text,
  p_comentario  text default null,
  p_id_asignado bigint default null
)
returns public.alarma
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_alarma public.alarma;
begin
  select * into v_alarma from public.alarma where id_alarma = p_id_alarma for update;
  if v_alarma.id_alarma is null then
    raise exception 'Alarma % no existe', p_id_alarma using errcode = 'P0002';
  end if;
  if not public.tiene_permiso('ALARMAS_GESTIONAR', v_alarma.id_sucursal) then
    raise exception 'Sin permiso ALARMAS_GESTIONAR en la sucursal' using errcode = '42501';
  end if;
  if p_estado not in ('VISTA', 'EN_ATENCION', 'RESUELTA') then
    raise exception 'Estado no válido: %', p_estado using errcode = '22023';
  end if;
  if p_estado = 'RESUELTA' and p_comentario is null then
    raise exception 'Para resolver manualmente se requiere un comentario' using errcode = '22023';
  end if;

  update public.alarma
     set estado = p_estado,
         id_asignado = coalesce(p_id_asignado, id_asignado),
         resuelta = case when p_estado = 'RESUELTA' then now() end,
         actualizada = now()
   where id_alarma = p_id_alarma
  returning * into v_alarma;

  insert into public.alarma_historial (id_alarma, accion, comentario, id_usuario)
  values (p_id_alarma, p_estado, p_comentario, public.usuario_actual_id());

  return v_alarma;
end;
$$;
