-- =====================================================================
-- 0600 · Inventario: lotes, existencias y kardex (doc 05 §2.2, §3.5; doc 12 §3)
--
-- Regla de oro: NADIE actualiza "existencia" directamente. Todo cambio es
-- un INSERT en movimiento_inventario; el trigger de esta migración calcula
-- el saldo, el costo promedio (RN-14) y actualiza la existencia en la
-- misma transacción. Así el kardex y la existencia nunca se separan.
-- =====================================================================

create table public.lote (
  id_lote          bigint generated by default as identity primary key,
  id_producto      bigint      not null references public.producto,
  numero_lote      varchar(30) not null,
  fecha_caducidad  date,
  fecha_recepcion  date        not null default current_date,
  bloqueado        boolean     not null default false,      -- RN-EXI-03 / RN-11
  unique (id_producto, numero_lote),
  unique (id_lote, id_producto)                              -- para la FK compuesta
);
create index lote_caducidad_idx on public.lote (fecha_caducidad) where fecha_caducidad is not null;

-- Saldo actual por almacén, producto y lote. id_lote nulo = producto sin
-- control de lote (D-04: en lugar del "0" del doc 05, que rompía la FK).
create table public.existencia (
  id_existencia  bigint generated by default as identity primary key,
  id_almacen     bigint        not null references public.almacen,
  id_producto    bigint        not null references public.producto,
  id_lote        bigint,
  cantidad       numeric(12,3) not null default 0,
  actualizado    timestamptz   not null default now(),
  constraint existencia_unica unique nulls not distinct (id_almacen, id_producto, id_lote),
  foreign key (id_lote, id_producto) references public.lote (id_lote, id_producto)
);
create index existencia_producto_idx on public.existencia (id_producto);

create table public.movimiento_inventario (
  id_movimiento              bigint generated by default as identity primary key,
  id_producto                bigint        not null references public.producto,
  id_almacen                 bigint        not null references public.almacen,
  id_sucursal                bigint        not null references public.sucursal,  -- lo llena el trigger
  id_lote                    bigint,
  tipo                       varchar(12)   not null check (tipo in (
                               'INICIAL', 'COMPRA', 'VENTA', 'CANCEL_VENTA', 'DEVOL_CLI', 'DEVOL_PROV',
                               'AJUSTE', 'MERMA', 'TRANSF_SAL', 'TRANSF_ENT')),
  cantidad                   numeric(12,3) not null,      -- + entrada, - salida
  costo_unitario             numeric(12,4) not null,      -- si no se manda, el trigger usa el promedio
  existencia_resultante      numeric(12,3) not null,      -- lo calcula el trigger
  costo_promedio_resultante  numeric(12,4) not null,      -- lo calcula el trigger
  documento_origen           varchar(60)   not null,      -- "venta:6f1c...", "recepcion:12", "ajuste:7"
  id_usuario                 bigint        references public.usuario,
  fecha                      timestamptz   not null default now(),
  foreign key (id_lote, id_producto) references public.lote (id_lote, id_producto),
  -- El signo debe corresponder al tipo de movimiento.
  check (cantidad <> 0),
  check (case
           when tipo in ('INICIAL', 'COMPRA', 'CANCEL_VENTA', 'DEVOL_CLI', 'TRANSF_ENT') then cantidad > 0
           when tipo in ('VENTA', 'MERMA', 'DEVOL_PROV', 'TRANSF_SAL')                   then cantidad < 0
           else true                                                                     -- AJUSTE: ±
         end),
  check (costo_unitario >= 0)
);
-- Índice del kardex (doc 05 §5).
create index movimiento_kardex_idx on public.movimiento_inventario (id_producto, id_almacen, fecha);
create index movimiento_sucursal_fecha_idx on public.movimiento_inventario (id_sucursal, fecha);

comment on table public.movimiento_inventario is
  'Kardex. Solo inserción (RF-KDX-01): las correcciones se hacen con un movimiento contrario.';

-- ---------------------------------------------------------------------
-- Trigger que aplica el movimiento.
-- SECURITY DEFINER: lo dispara una función de negocio (venta, recepción,
-- ajuste) y debe poder actualizar "existencia" aunque el usuario no tenga
-- permiso directo sobre esa tabla.
-- ---------------------------------------------------------------------
create or replace function public.tg_movimiento_aplicar()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_saldo_almacen   numeric(12,3);
  v_total_producto  numeric(12,3);
  v_promedio        numeric(12,4);
  v_costo_entrada   numeric(12,4);
begin
  select a.id_sucursal into new.id_sucursal
  from public.almacen a where a.id_almacen = new.id_almacen;

  -- Asegura que exista la fila de saldo y la bloquea: dos cajas que venden
  -- el mismo producto en el mismo almacén se forman en fila aquí.
  insert into public.existencia (id_almacen, id_producto, id_lote, cantidad)
  values (new.id_almacen, new.id_producto, new.id_lote, 0)
  on conflict on constraint existencia_unica do nothing;

  select e.cantidad into v_saldo_almacen
  from public.existencia e
  where e.id_almacen = new.id_almacen
    and e.id_producto = new.id_producto
    and e.id_lote is not distinct from new.id_lote
  for update;

  new.existencia_resultante := v_saldo_almacen + new.cantidad;

  -- RF-EXI-05: ajustes negativos, mermas, transferencias y devoluciones a
  -- proveedor no pueden sacar más de lo que hay. Las VENTAS sí pueden dejar
  -- negativo (RN-02, venta autorizada o sin conexión) y generan alarma.
  if new.cantidad < 0
     and new.existencia_resultante < 0
     and new.tipo in ('AJUSTE', 'MERMA', 'TRANSF_SAL', 'DEVOL_PROV') then
    raise exception 'Existencia insuficiente: hay %, se intentan sacar %', v_saldo_almacen, -new.cantidad
      using errcode = 'P0001', hint = 'EXISTENCIA_INSUFICIENTE';
  end if;

  -- Costo promedio ponderado global del producto (RN-14). El candado sobre
  -- producto serializa las entradas concurrentes del mismo artículo.
  select p.costo_promedio into v_promedio
  from public.producto p where p.id_producto = new.id_producto
  for update;

  if new.cantidad > 0 then
    v_costo_entrada := coalesce(new.costo_unitario, v_promedio);

    select coalesce(sum(e.cantidad), 0) into v_total_producto
    from public.existencia e where e.id_producto = new.id_producto;

    if v_total_producto <= 0 then
      v_promedio := v_costo_entrada;     -- sin existencia previa, el costo es el de la entrada
    else
      v_promedio := round(
        (v_total_producto * v_promedio + new.cantidad * v_costo_entrada)
        / (v_total_producto + new.cantidad), 4);
    end if;

    update public.producto set costo_promedio = v_promedio where id_producto = new.id_producto;
    new.costo_unitario := v_costo_entrada;
  else
    new.costo_unitario := coalesce(new.costo_unitario, v_promedio);   -- las salidas salen al promedio
  end if;

  new.costo_promedio_resultante := v_promedio;
  new.id_usuario := coalesce(new.id_usuario, public.usuario_actual_id());

  update public.existencia
     set cantidad = new.existencia_resultante, actualizado = now()
   where id_almacen = new.id_almacen
     and id_producto = new.id_producto
     and id_lote is not distinct from new.id_lote;

  return new;
end;
$$;

create trigger movimiento_aplicar
  before insert on public.movimiento_inventario
  for each row execute function public.tg_movimiento_aplicar();

create trigger movimiento_solo_insercion
  before update or delete on public.movimiento_inventario
  for each row execute function public.tg_solo_insercion();

-- ---------------------------------------------------------------------
-- Documentos que originan movimientos
-- ---------------------------------------------------------------------
create table public.ajuste_inventario (
  id_ajuste    bigint generated by default as identity primary key,
  id_almacen   bigint       not null references public.almacen,
  motivo       varchar(12)  not null check (motivo in ('CADUCIDAD', 'DAÑO', 'ROBO', 'CONSUMO', 'CORRECCION')),
  comentario   varchar(250),
  estado       varchar(10)  not null default 'PENDIENTE' check (estado in ('PENDIENTE', 'APLICADO', 'RECHAZADO')),
  id_usuario   bigint       not null references public.usuario,
  id_autoriza  bigint       references public.usuario,
  fecha        timestamptz  not null default now(),
  check (id_autoriza is null or id_autoriza <> id_usuario)          -- RN-ROL-01
);

create table public.ajuste_detalle (
  id_ajuste    bigint        not null references public.ajuste_inventario on delete cascade,
  id_producto  bigint        not null references public.producto,
  id_lote      bigint        references public.lote,
  cantidad     numeric(12,3) not null check (cantidad <> 0),        -- ± según el ajuste
  costo        numeric(12,4),
  primary key (id_ajuste, id_producto)
);

-- Fase 2 (doc 07 §3.1): transferencias y conteos. Se dejan modelados.
create table public.transferencia (
  id_transferencia    bigint generated by default as identity primary key,
  id_almacen_origen   bigint      not null references public.almacen,
  id_almacen_destino  bigint      not null references public.almacen,
  estado              varchar(10) not null default 'SOLICITADA'
                      check (estado in ('SOLICITADA', 'ENVIADA', 'RECIBIDA', 'CANCELADA')),
  fecha_envio         timestamptz,
  fecha_recepcion     timestamptz,
  check (id_almacen_origen <> id_almacen_destino)
);

create table public.transferencia_detalle (
  id_transferencia   bigint        not null references public.transferencia on delete cascade,
  id_producto        bigint        not null references public.producto,
  cantidad_enviada   numeric(12,3) not null check (cantidad_enviada > 0),
  cantidad_recibida  numeric(12,3) check (cantidad_recibida >= 0),
  primary key (id_transferencia, id_producto)
);

create table public.conteo_fisico (
  id_conteo    bigint generated by default as identity primary key,
  id_almacen   bigint      not null references public.almacen,
  tipo         varchar(8)  not null check (tipo in ('TOTAL', 'CICLICO')),
  estado       varchar(8)  not null default 'ABIERTO' check (estado in ('ABIERTO', 'CERRADO', 'APLICADO')),
  fecha_corte  timestamptz not null default now()
);

create table public.conteo_detalle (
  id_conteo    bigint        not null references public.conteo_fisico on delete cascade,
  id_producto  bigint        not null references public.producto,
  teorico      numeric(12,3) not null,
  contado      numeric(12,3),
  diferencia   numeric(12,3) generated always as (contado - teorico) stored,
  primary key (id_conteo, id_producto)
);
