-- =====================================================================
-- 0500 · Facturación SAR: emisor, establecimientos, puntos de emisión y CAI
-- (doc 09 §9). Aquí va la ESTRUCTURA y sus reglas de integridad.
-- La asignación de correlativos (siguiente_correlativo) y la emisión son
-- del módulo de negocio y SAR.
-- =====================================================================

create table public.config_fiscal (
  id_empresa                bigint       primary key references public.empresa,
  rtn                       char(14)     not null check (public.rtn_valido(rtn)),
  razon_social              varchar(150) not null,
  nombre_comercial          varchar(120),
  direccion_casa_matriz     varchar(250) not null,
  telefono                  varchar(20),
  correo                    varchar(120),
  resolucion_autoimpresor   varchar(60),
  fecha_resolucion          date,
  leyenda_factura           varchar(250) default 'La factura es beneficio de todos. Exíjala.',
  permitir_ticket_no_fiscal boolean      not null default false,   -- ADR-06: desactivado por defecto
  dias_canje_ticket         int          not null default 30 check (dias_canje_ticket between 0 and 365),
  documento_por_defecto     varchar(12)  not null default 'FACTURA_CF'
                            check (documento_por_defecto in ('TICKET', 'FACTURA_CF', 'FACTURA_RTN'))
);

-- RF-DOC-02: la sucursal puede sobrescribir el documento por defecto y si se permite ticket.
alter table public.sucursal
  add column documento_por_defecto varchar(12)
      check (documento_por_defecto in ('TICKET', 'FACTURA_CF', 'FACTURA_RTN')),
  add column permitir_ticket boolean;

create table public.establecimiento_sar (
  id_establecimiento  bigint generated by default as identity primary key,
  id_sucursal         bigint       not null unique references public.sucursal,
  codigo              char(3)      not null unique check (codigo ~ '^[0-9]{3}$'),
  direccion           varchar(250) not null,
  activo              boolean      not null default true
);

create table public.punto_emision (
  id_punto            bigint generated by default as identity primary key,
  id_establecimiento  bigint  not null references public.establecimiento_sar,
  id_caja             bigint  unique references public.caja,
  codigo              char(3) not null check (codigo ~ '^[0-9]{3}$'),
  activo              boolean not null default true,
  unique (id_establecimiento, codigo)
);

create table public.tipo_documento_fiscal (
  codigo               char(2)     primary key check (codigo ~ '^[0-9]{2}$'),   -- 01 = Factura
  nombre               varchar(60) not null,
  afecta_libro_ventas  boolean     not null default true
);

create table public.cai (
  id_cai                   bigint generated by default as identity primary key,
  cai                      char(37)    not null unique
                           check (cai ~ '^[0-9A-F]{6}-[0-9A-F]{6}-[0-9A-F]{6}-[0-9A-F]{6}-[0-9A-F]{6}-[0-9A-F]{2}$'),
  id_punto                 bigint      not null references public.punto_emision,
  tipo_documento           char(2)     not null references public.tipo_documento_fiscal,
  fecha_autorizacion       date        not null,
  correlativo_inicial      bigint      not null check (correlativo_inicial between 1 and 99999999),
  correlativo_final        bigint      not null check (correlativo_final between 1 and 99999999),
  ultimo_usado             bigint,                                  -- nulo = no se ha usado
  fecha_limite_emision     date        not null,
  umbral_alerta_pct        int         not null default 90 check (umbral_alerta_pct between 1 and 100),
  dias_alerta_vencimiento  int         not null default 30 check (dias_alerta_vencimiento between 0 and 365),
  estado                   varchar(10) not null default 'EN_ESPERA'
                           check (estado in ('EN_ESPERA', 'ACTIVO', 'AGOTADO', 'VENCIDO', 'INACTIVO')),
  motivo_inactivacion      varchar(250),
  archivo_soporte_url      text,
  id_usuario_registro      bigint      references public.usuario,
  creado                   timestamptz not null default now(),
  check (correlativo_final >= correlativo_inicial),
  check (fecha_limite_emision >= fecha_autorizacion),
  check (ultimo_usado is null or ultimo_usado between correlativo_inicial and correlativo_final),
  check (estado <> 'INACTIVO' or motivo_inactivacion is not null),
  -- RN-SAR-04: los rangos de un mismo punto y tipo no se traslapan.
  constraint cai_rango_sin_traslape exclude using gist (
    id_punto with =,
    tipo_documento with =,
    int8range(correlativo_inicial, correlativo_final, '[]') with &&
  )
);
-- RN-SAR-03: solo un CAI activo por punto de emisión y tipo de documento.
create unique index cai_un_activo_idx on public.cai (id_punto, tipo_documento) where estado = 'ACTIVO';

-- Bloques reservados para facturar sin conexión (fase 2, RF-SAR-13).
create table public.bloque_correlativo (
  id_bloque  bigint generated by default as identity primary key,
  id_cai     bigint      not null references public.cai,
  desde      bigint      not null,
  hasta      bigint      not null,
  asignado   timestamptz not null default now(),
  estado     varchar(10) not null default 'RESERVADO' check (estado in ('RESERVADO', 'EN_USO', 'CERRADO')),
  check (hasta >= desde),
  constraint bloque_sin_traslape exclude using gist (
    id_cai with =, int8range(desde, hasta, '[]') with &&
  )
);

-- Número fiscal completo: EEE-PPP-TT-NNNNNNNN (000-003-01-00012520).
create or replace function public.formato_numero_fiscal(p_id_cai bigint, p_correlativo bigint)
returns text
language sql
stable
set search_path = ''
as $$
  select e.codigo || '-' || pe.codigo || '-' || c.tipo_documento || '-' || lpad(p_correlativo::text, 8, '0')
  from public.cai c
  join public.punto_emision pe on pe.id_punto = c.id_punto
  join public.establecimiento_sar e on e.id_establecimiento = pe.id_establecimiento
  where c.id_cai = p_id_cai
$$;
