-- =====================================================================
-- 0400 · Catálogo y precios (doc 05 §2.1 y §3.1–3.2, doc 12 §5)
-- =====================================================================

create extension if not exists pg_trgm with schema extensions;

-- Honduras: el impuesto depende de la clasificación fiscal del producto
-- (doc 09). Reemplaza a IMPUESTO/PRODUCTO_IMPUESTO del modelo genérico (D-03).
create table public.clasificacion_fiscal (
  codigo       varchar(10)  primary key check (codigo in ('EXENTO', 'GRAVADO15', 'GRAVADO18')),
  tasa         numeric(5,4) not null check (tasa >= 0 and tasa < 1),
  descripcion  varchar(120) not null
);

create table public.categoria (
  id_categoria        bigint generated by default as identity primary key,
  id_categoria_padre  bigint references public.categoria,
  nombre              varchar(60)  not null,
  margen_objetivo     numeric(5,4) check (margen_objetivo between 0 and 1),
  permite_negativo    boolean      not null default false,   -- RN-02 (frutas, verduras)
  activa              boolean      not null default true,
  unique (id_categoria_padre, nombre),
  check (id_categoria_padre is distinct from id_categoria)
);

create table public.marca (
  id_marca  bigint generated by default as identity primary key,
  nombre    varchar(60) not null unique
);

create table public.unidad_medida (
  id_unidad  bigint generated by default as identity primary key,
  clave      varchar(5)  not null unique,     -- PZA, KG, LT
  nombre     varchar(30) not null,
  decimales  smallint    not null default 0 check (decimales between 0 and 3)
);

create table public.producto (
  id_producto           bigint generated by default as identity primary key,
  sku                   varchar(20)   not null unique,
  descripcion           varchar(120)  not null,
  id_categoria          bigint        not null references public.categoria,
  id_marca              bigint        references public.marca,
  id_unidad             bigint        not null references public.unidad_medida,
  clasificacion_fiscal  varchar(10)   not null default 'GRAVADO15' references public.clasificacion_fiscal,
  contenido             varchar(30),                  -- "2 L", "500 g"
  es_granel             boolean       not null default false,
  controla_lote         boolean       not null default false,
  restringido_edad      boolean       not null default false,   -- RN-16
  excluido_puntos       boolean       not null default false,   -- RN-09
  costo_promedio        numeric(12,4) not null default 0 check (costo_promedio >= 0),  -- RN-14
  stock_minimo          numeric(12,3) not null default 0 check (stock_minimo >= 0),
  punto_reorden         numeric(12,3) check (punto_reorden >= 0),
  stock_maximo          numeric(12,3) check (stock_maximo >= 0),
  foto_url              text,
  activo                boolean       not null default true,    -- baja lógica, nunca se borra
  creado                timestamptz   not null default now(),
  actualizado           timestamptz   not null default now(),
  check (stock_maximo is null or stock_maximo >= stock_minimo)
);
create index producto_categoria_idx on public.producto (id_categoria);
-- Búsqueda por nombre en caja (F2) con coincidencias parciales.
create index producto_descripcion_trgm_idx on public.producto
  using gin (descripcion extensions.gin_trgm_ops);

create trigger producto_actualizado
  before update on public.producto
  for each row execute function public.tg_marcar_actualizado();

create table public.codigo_barras (
  codigo                varchar(20)   primary key,
  id_producto           bigint        not null references public.producto,
  tipo                  varchar(15)   not null default 'EAN13'
                        check (tipo in ('EAN13', 'EAN8', 'UPC', 'INTERNO', 'PESO_VARIABLE')),
  factor                numeric(10,3) not null default 1 check (factor > 0),   -- 1 = pieza, 12 = caja
  generado_por_sistema  boolean       not null default false,
  id_usuario_registro   bigint        references public.usuario,
  creado                timestamptz   not null default now(),
  -- RN-21: todo código se valida con su dígito verificador.
  check (case tipo
           when 'EAN13'         then public.ean13_valido(codigo)
           when 'INTERNO'       then public.ean13_valido(codigo) and codigo like '200%'
           when 'PESO_VARIABLE' then codigo ~ '^2[0-9]{5}$'   -- prefijo PLU de báscula
           when 'EAN8'          then codigo ~ '^[0-9]{8}$'
           when 'UPC'           then codigo ~ '^[0-9]{12}$'
         end)
);
create index codigo_barras_producto_idx on public.codigo_barras (id_producto);

-- Secuencia de códigos internos (prefijo 200). La función que la consume,
-- generar_codigo_interno(), es del módulo de negocio y debe tomar la fila
-- con FOR UPDATE para no repetir números.
create table public.secuencia_codigo_interno (
  prefijo       varchar(3) primary key check (prefijo ~ '^2[0-9]{2}$'),
  ultimo_valor  bigint     not null default 0 check (ultimo_valor between 0 and 999999999)
);

-- Precio por sucursal con vigencia (RF-CAT-03). id_sucursal nulo = precio
-- general. El historial nunca se borra: un precio nuevo cierra el anterior.
create table public.precio (
  id_precio          bigint generated by default as identity primary key,
  id_producto        bigint        not null references public.producto,
  id_sucursal        bigint        references public.sucursal,
  precio_venta       numeric(12,2) not null check (precio_venta > 0),   -- incluye ISV
  vigente_desde      timestamptz   not null default now(),
  vigente_hasta      timestamptz,
  id_usuario_cambio  bigint        not null references public.usuario,
  creado             timestamptz   not null default now(),
  check (vigente_hasta is null or vigente_hasta > vigente_desde),
  -- Doc 05 §3.2: no pueden existir dos precios con vigencias traslapadas
  -- para el mismo producto y sucursal.
  constraint precio_sin_traslape exclude using gist (
    id_producto with =,
    (coalesce(id_sucursal, 0)) with =,
    tstzrange(vigente_desde, vigente_hasta, '[)') with &&
  )
);
create index precio_vigente_idx on public.precio (id_producto, id_sucursal, vigente_desde desc);

-- Precio que aplica a un producto en una sucursal y momento dados:
-- primero el de la sucursal y, si no hay, el general.
create or replace function public.precio_vigente(
  p_id_producto bigint,
  p_id_sucursal bigint,
  p_fecha       timestamptz default now()
)
returns numeric
language sql
stable
set search_path = ''
as $$
  select p.precio_venta
  from public.precio p
  where p.id_producto = p_id_producto
    and (p.id_sucursal = p_id_sucursal or p.id_sucursal is null)
    and p.vigente_desde <= p_fecha
    and (p.vigente_hasta is null or p.vigente_hasta > p_fecha)
  order by p.id_sucursal nulls last
  limit 1
$$;

-- Programa un precio nuevo: cierra la vigencia abierta (si empieza antes)
-- e inserta el nuevo, en una sola transacción. Lo usa PUT /productos/{id}/precios.
create or replace function public.programar_precio(
  p_id_producto  bigint,
  p_id_sucursal  bigint,
  p_precio       numeric,
  p_desde        timestamptz default now(),
  p_hasta        timestamptz default null
)
returns bigint
language plpgsql
set search_path = ''
as $$
declare
  v_usuario bigint := public.usuario_actual_id();
  v_id      bigint;
begin
  if v_usuario is null then
    raise exception 'Usuario no identificado' using errcode = '42501';
  end if;

  update public.precio
     set vigente_hasta = p_desde
   where id_producto = p_id_producto
     and id_sucursal is not distinct from p_id_sucursal
     and vigente_desde < p_desde
     and (vigente_hasta is null or vigente_hasta > p_desde);

  insert into public.precio (id_producto, id_sucursal, precio_venta, vigente_desde, vigente_hasta, id_usuario_cambio)
  values (p_id_producto, p_id_sucursal, p_precio, p_desde, p_hasta, v_usuario)
  returning id_precio into v_id;

  return v_id;
end;
$$;

-- Venta rápida táctil (doc 12 §1)
create table public.categoria_rapida (
  id_categoria_rapida  bigint generated by default as identity primary key,
  id_sucursal          bigint      not null references public.sucursal,
  nombre               varchar(30) not null,
  color                varchar(9),
  icono                varchar(30),
  orden                int         not null default 0,
  unique (id_sucursal, nombre)
);

create table public.boton_rapido (
  id_boton             bigint generated by default as identity primary key,
  id_categoria_rapida  bigint  not null references public.categoria_rapida on delete cascade,
  id_producto          bigint  not null references public.producto,
  orden                int     not null default 0,
  foto_url             text,
  automatico           boolean not null default false,
  unique (id_categoria_rapida, id_producto)
);

create table public.etiqueta_cola (
  id_etiqueta  bigint generated by default as identity primary key,
  id_producto  bigint      not null references public.producto,
  tipo         varchar(10) not null default 'PRODUCTO' check (tipo in ('PRODUCTO', 'ANAQUEL')),
  motivo       varchar(15) not null check (motivo in ('CODIGO_NUEVO', 'CAMBIO_PRECIO', 'PROMOCION', 'RECEPCION')),
  cantidad     int         not null default 1 check (cantidad > 0),
  estado       varchar(10) not null default 'PENDIENTE' check (estado in ('PENDIENTE', 'IMPRESA')),
  creado       timestamptz not null default now()
);
create index etiqueta_cola_pendiente_idx on public.etiqueta_cola (estado) where estado = 'PENDIENTE';
