-- =====================================================================
-- 0700 · Compras y proveedores (doc 05 §2.2)
-- Estructura. La lógica de aprobación y recepción es del módulo de negocio:
-- la recepción solo debe insertar movimientos tipo COMPRA; el costo
-- promedio lo calcula el trigger del kardex.
-- =====================================================================

create table public.proveedor (
  id_proveedor         bigint generated by default as identity primary key,
  razon_social         varchar(150) not null,
  rtn                  char(14)     unique check (rtn is null or public.rtn_valido(rtn)),
  contacto             varchar(120),
  correo               varchar(120),
  telefono             varchar(20),
  dias_credito         int          not null default 0 check (dias_credito >= 0),
  tiempo_entrega_dias  int          not null default 1 check (tiempo_entrega_dias >= 0),
  activo               boolean      not null default true
);

create table public.producto_proveedor (
  id_producto       bigint        not null references public.producto,
  id_proveedor      bigint        not null references public.proveedor,
  codigo_proveedor  varchar(30),
  costo_pactado     numeric(12,4) check (costo_pactado >= 0),
  empaque           numeric(10,3) not null default 1 check (empaque > 0),
  principal         boolean       not null default false,
  primary key (id_producto, id_proveedor)
);
create unique index producto_proveedor_principal_idx
  on public.producto_proveedor (id_producto) where principal;

create table public.orden_compra (
  id_oc          bigint generated by default as identity primary key,
  folio          varchar(20)   not null unique,
  id_proveedor   bigint        not null references public.proveedor,
  id_sucursal    bigint        not null references public.sucursal,
  estado         varchar(12)   not null default 'BORRADOR' check (estado in (
                   'BORRADOR', 'POR_APROBAR', 'APROBADA', 'ENVIADA', 'PARCIAL', 'RECIBIDA', 'CANCELADA')),
  fecha          timestamptz   not null default now(),
  fecha_entrega  date,
  subtotal       numeric(12,2) not null default 0,
  impuestos      numeric(12,2) not null default 0,
  total          numeric(12,2) not null default 0,
  id_elabora     bigint        not null references public.usuario,
  id_aprueba     bigint        references public.usuario,
  check (id_aprueba is null or id_aprueba <> id_elabora)          -- RN-ROL-01
);
create index orden_compra_sucursal_idx on public.orden_compra (id_sucursal, estado);

create table public.oc_detalle (
  id_oc              bigint        not null references public.orden_compra on delete cascade,
  id_producto        bigint        not null references public.producto,
  cantidad           numeric(12,3) not null check (cantidad > 0),
  costo_unitario     numeric(12,4) not null check (costo_unitario >= 0),
  cantidad_recibida  numeric(12,3) not null default 0 check (cantidad_recibida >= 0),
  primary key (id_oc, id_producto)
);

create table public.recepcion (
  id_recepcion       bigint generated by default as identity primary key,
  id_oc              bigint      references public.orden_compra,
  id_almacen         bigint      not null references public.almacen,
  factura_proveedor  varchar(40),
  fecha              timestamptz not null default now(),
  id_recibe          bigint      not null references public.usuario
);

create table public.recepcion_detalle (
  id_recepcion    bigint        not null references public.recepcion on delete cascade,
  id_producto     bigint        not null references public.producto,
  id_lote         bigint        references public.lote,
  cantidad        numeric(12,3) not null check (cantidad > 0),
  costo_unitario  numeric(12,4) not null check (costo_unitario >= 0),
  primary key (id_recepcion, id_producto)
);

-- Fase 2: cuentas por pagar.
create table public.cuenta_por_pagar (
  id_cxp        bigint generated by default as identity primary key,
  id_recepcion  bigint        unique references public.recepcion,
  id_proveedor  bigint        not null references public.proveedor,
  importe       numeric(12,2) not null check (importe >= 0),
  saldo         numeric(12,2) not null check (saldo >= 0),
  vencimiento   date          not null,
  estado        varchar(10)   not null default 'PENDIENTE' check (estado in ('PENDIENTE', 'PARCIAL', 'PAGADA')),
  check (saldo <= importe)
);

create table public.pago_proveedor (
  id_pago     bigint generated by default as identity primary key,
  id_cxp      bigint        not null references public.cuenta_por_pagar,
  importe     numeric(12,2) not null check (importe > 0),
  fecha       date          not null default current_date,
  referencia  varchar(60)
);
