-- =====================================================================
-- 0300 · Seguridad: usuarios, roles, permisos y bitácora (doc 10 §9)
-- El inicio de sesión lo maneja Supabase Auth (auth.users); aquí solo
-- vive el perfil del empleado y sus permisos.
-- =====================================================================

create table public.usuario (
  id_usuario          bigint generated by default as identity primary key,
  auth_user_id        uuid         unique references auth.users (id) on delete set null,
  nombre_completo     varchar(120) not null,
  usuario             varchar(40)  not null unique,
  hash_pin            text,                       -- PIN de caja (lo valida el backend)
  tarjeta_proximidad  varchar(40)  unique,
  intentos_fallidos   int          not null default 0,
  bloqueado_hasta     timestamptz,
  activo              boolean      not null default true,
  ultimo_acceso       timestamptz,
  creado              timestamptz  not null default now()
);
comment on column public.usuario.auth_user_id is 'Cuenta de Supabase Auth. Nulo para empleados que solo usan PIN en caja.';

create table public.rol (
  id_rol       bigint generated by default as identity primary key,
  nombre       varchar(40) not null unique,
  descripcion  varchar(200),
  alcance      varchar(12) not null default 'ASIGNADAS'
               check (alcance in ('TODAS', 'ASIGNADAS', 'PROPIA_CAJA')),
  hora_inicio  time,
  hora_fin     time,
  dias         varchar(7),                         -- LMXJVSD
  sistema      boolean     not null default false, -- predefinido
  activo       boolean     not null default true
);

create table public.permiso (
  id_permiso   bigint generated by default as identity primary key,
  clave        varchar(40)  not null unique check (clave ~ '^[A-Z_]+$'),
  modulo       varchar(30)  not null,
  descripcion  varchar(200) not null
);

-- Decisión (docs/decisiones.md, D-05): cada permiso es una clave granular
-- (VENTA_CREAR, VENTA_CANCELAR...). Tener la fila = tener el permiso.
-- "puede_autorizar" marca los permisos que el rol puede autorizar a otros (A).
create table public.rol_permiso (
  id_rol           bigint  not null references public.rol on delete cascade,
  id_permiso       bigint  not null references public.permiso on delete cascade,
  puede_autorizar  boolean not null default false,
  primary key (id_rol, id_permiso)
);
create index rol_permiso_permiso_idx on public.rol_permiso (id_permiso);

create table public.rol_limite (
  id_rol       bigint        not null references public.rol on delete cascade,
  tipo_limite  varchar(20)   not null
               check (tipo_limite in ('DESCUENTO_PCT', 'DEVOLUCION_MONTO', 'OC_MONTO', 'RETIRO_MONTO')),
  valor        numeric(12,2) not null check (valor >= 0),
  primary key (id_rol, tipo_limite)
);

create table public.usuario_rol (
  id_usuario       bigint not null references public.usuario on delete cascade,
  id_rol           bigint not null references public.rol on delete cascade,
  vigente_desde    date   not null default current_date,
  vigente_hasta    date,                           -- nulo = permanente; con fecha = delegación
  id_asignado_por  bigint references public.usuario,
  primary key (id_usuario, id_rol),
  check (vigente_hasta is null or vigente_hasta >= vigente_desde)
);
create index usuario_rol_rol_idx on public.usuario_rol (id_rol);

create table public.usuario_sucursal (
  id_usuario   bigint not null references public.usuario on delete cascade,
  id_sucursal  bigint not null references public.sucursal on delete cascade,
  primary key (id_usuario, id_sucursal)
);
create index usuario_sucursal_sucursal_idx on public.usuario_sucursal (id_sucursal);

create table public.regla_segregacion (
  id_permiso_a  bigint      not null references public.permiso on delete cascade,
  id_permiso_b  bigint      not null references public.permiso on delete cascade,
  accion        varchar(10) not null default 'ADVERTIR' check (accion in ('ADVERTIR', 'BLOQUEAR')),
  primary key (id_permiso_a, id_permiso_b),
  check (id_permiso_a <> id_permiso_b)
);

create table public.autorizacion (
  id_autorizacion  bigint generated by default as identity primary key,
  id_autorizador   bigint       not null references public.usuario,
  id_solicitante   bigint       not null references public.usuario,
  permiso          varchar(40)  not null,
  entidad          varchar(40)  not null,
  id_entidad       varchar(60)  not null,
  motivo           varchar(250) not null,
  fecha            timestamptz  not null default now(),
  check (id_autorizador <> id_solicitante)          -- RN-ROL-01
);

create table public.bitacora_auditoria (
  id_bitacora      bigint generated by default as identity primary key,
  id_usuario       bigint references public.usuario,
  accion           varchar(40)  not null,
  entidad          varchar(40)  not null,
  id_entidad       varchar(60),
  valor_anterior   jsonb,
  valor_nuevo      jsonb,
  terminal         varchar(60),
  ip               inet,
  fecha            timestamptz  not null default now(),
  hash_encadenado  text
);
create index bitacora_entidad_idx on public.bitacora_auditoria (entidad, id_entidad, fecha);

-- RN-18: la bitácora no se modifica ni se borra, ni siquiera desde el backend.
create trigger bitacora_solo_insercion
  before update or delete on public.bitacora_auditoria
  for each row execute function public.tg_solo_insercion();

-- =====================================================================
-- Funciones de identidad usadas por las políticas RLS (doc 10 §9.1).
-- Son SECURITY DEFINER para leer usuario_rol/rol_permiso sin chocar con
-- el RLS de esas mismas tablas (evita recursión infinita), y fijan
-- search_path vacío para que nadie las secuestre con un esquema propio.
-- Contrato acordado con el dev de seguridad: firma tiene_permiso(clave, sucursal).
-- =====================================================================

-- Empleado (public.usuario) del JWT actual, o nulo si no hay sesión o está inactivo/bloqueado.
create or replace function public.usuario_actual_id()
returns bigint
language sql
stable
security definer
set search_path = ''
as $$
  select u.id_usuario
  from public.usuario u
  where u.auth_user_id = auth.uid()
    and u.activo
    and (u.bloqueado_hasta is null or u.bloqueado_hasta < now())
$$;

-- ¿El usuario autenticado tiene el permiso en esa sucursal?
-- p_id_sucursal nulo = "en alguna sucursal" (catálogos globales).
-- RN-ROL-04: con varios roles, los permisos se suman (basta uno).
-- RN-ROL-08: un usuario dado de baja pierde el acceso de inmediato.
create or replace function public.tiene_permiso(p_clave text, p_id_sucursal bigint default null)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from public.usuario u
    join public.usuario_rol ur on ur.id_usuario = u.id_usuario
    join public.rol r          on r.id_rol = ur.id_rol and r.activo
    join public.rol_permiso rp on rp.id_rol = r.id_rol
    join public.permiso p      on p.id_permiso = rp.id_permiso
    where u.auth_user_id = auth.uid()
      and u.activo
      and (u.bloqueado_hasta is null or u.bloqueado_hasta < now())
      and p.clave = p_clave
      and ur.vigente_desde <= current_date
      and (ur.vigente_hasta is null or ur.vigente_hasta >= current_date)
      and (
        p_id_sucursal is null
        or r.alcance = 'TODAS'
        or exists (select 1 from public.usuario_sucursal us
                   where us.id_usuario = u.id_usuario and us.id_sucursal = p_id_sucursal)
      )
  )
$$;

-- Sucursales en las que el usuario puede operar (para filtros de reportes).
create or replace function public.sucursales_del_usuario()
returns setof bigint
language sql
stable
security definer
set search_path = ''
as $$
  select s.id_sucursal
  from public.sucursal s
  where exists (
    select 1
    from public.usuario u
    join public.usuario_rol ur on ur.id_usuario = u.id_usuario
    join public.rol r on r.id_rol = ur.id_rol and r.activo
    where u.auth_user_id = auth.uid() and u.activo
      and ur.vigente_desde <= current_date
      and (ur.vigente_hasta is null or ur.vigente_hasta >= current_date)
      and (r.alcance = 'TODAS'
           or exists (select 1 from public.usuario_sucursal us
                      where us.id_usuario = u.id_usuario and us.id_sucursal = s.id_sucursal))
  )
$$;
