-- =====================================================================
-- 0800 · Clientes y lealtad (doc 05 §3.7, RF-CLI) + estructura de promociones
-- =====================================================================

create table public.cliente (
  id_cliente            bigint generated by default as identity primary key,
  nombre                varchar(120) not null,
  telefono              varchar(15)  unique check (telefono ~ '^[0-9+]{8,15}$'),  -- identificación en caja
  correo                varchar(120) check (correo ~* '^[^@\s]+@[^@\s]+\.[^@\s]+$'),
  fecha_nacimiento      date,
  rtn                   char(14)     check (rtn is null or public.rtn_valido(rtn)),
  razon_social          varchar(150),
  consentimiento_datos  boolean      not null check (consentimiento_datos),   -- RF-CLI-01: obligatorio
  fecha_consentimiento  timestamptz  not null default now(),
  anonimizado           boolean      not null default false,                  -- RF-CLI-06 (ARCO)
  activo                boolean      not null default true,
  creado                timestamptz  not null default now(),
  check (rtn is null or razon_social is not null),     -- factura con RTN exige razón social
  check (anonimizado or telefono is not null)          -- el teléfono solo se borra al anonimizar
);
create index cliente_rtn_idx on public.cliente (rtn) where rtn is not null;
comment on table public.cliente is 'Datos personales: nombre, teléfono, correo y fecha de nacimiento (doc 05 §3.7).';

create table public.config_lealtad (
  id_empresa          bigint        primary key references public.empresa,
  lempiras_por_punto  numeric(10,2) not null default 10 check (lempiras_por_punto > 0),   -- RF-CLI-02
  meses_caducidad     int           not null default 12 check (meses_caducidad > 0)      -- RN-10
);

create table public.cuenta_lealtad (
  id_cuenta       bigint generated by default as identity primary key,
  id_cliente      bigint      not null unique references public.cliente,
  numero_tarjeta  varchar(20) not null unique,
  saldo_puntos    int         not null default 0 check (saldo_puntos >= 0),   -- no se canjea más de lo que hay
  nivel           varchar(10) not null default 'BASICO',
  creada          timestamptz not null default now()
);

create table public.movimiento_puntos (
  id_mov      bigint generated by default as identity primary key,
  id_cuenta   bigint      not null references public.cuenta_lealtad,
  id_venta    uuid,                                        -- FK se agrega en 0900
  tipo        varchar(8)  not null check (tipo in ('ACUMULA', 'CANJE', 'CADUCA', 'AJUSTE')),
  puntos      int         not null check (puntos <> 0),
  caduca_el   date,
  fecha       timestamptz not null default now(),
  check (case tipo
           when 'ACUMULA' then puntos > 0 and caduca_el is not null
           when 'AJUSTE'  then true
           else puntos < 0
         end)
);
create index movimiento_puntos_cuenta_idx on public.movimiento_puntos (id_cuenta, fecha);

-- Cada cliente nuevo recibe su cuenta de lealtad automáticamente.
create or replace function public.tg_cliente_crear_cuenta()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into public.cuenta_lealtad (id_cliente, numero_tarjeta)
  values (new.id_cliente, 'MC' || lpad(new.id_cliente::text, 10, '0'));
  return new;
end;
$$;

create trigger cliente_crear_cuenta
  after insert on public.cliente
  for each row execute function public.tg_cliente_crear_cuenta();

-- El saldo se mueve solo por movimientos (igual que el kardex).
create or replace function public.tg_puntos_aplicar()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  update public.cuenta_lealtad
     set saldo_puntos = saldo_puntos + new.puntos
   where id_cuenta = new.id_cuenta;
  return new;
end;
$$;

create trigger puntos_aplicar
  after insert on public.movimiento_puntos
  for each row execute function public.tg_puntos_aplicar();

create trigger puntos_solo_insercion
  before update or delete on public.movimiento_puntos
  for each row execute function public.tg_solo_insercion();

-- Puntos que genera un importe pagado (RN-09: sobre lo pagado, sin productos
-- excluidos; quien llama ya restó los excluidos). Redondea hacia abajo.
create or replace function public.calcular_puntos(p_importe numeric, p_id_empresa bigint default 1)
returns int
language sql
stable
set search_path = ''
as $$
  select coalesce(floor(greatest(p_importe, 0) / c.lempiras_por_punto)::int, 0)
  from public.config_lealtad c
  where c.id_empresa = p_id_empresa
$$;

-- RF-CLI-06 (derecho de cancelación): borra los datos personales pero
-- conserva el registro para no romper ventas ni facturas históricas.
-- Corre con los permisos de quien llama: la política RLS de UPDATE exige
-- CLIENTE_DATOS_PERSONALES.
create or replace function public.anonimizar_cliente(p_id_cliente bigint)
returns void
language plpgsql
set search_path = ''
as $$
begin
  update public.cliente
     set nombre = 'Cliente anonimizado #' || id_cliente,
         telefono = null, correo = null, fecha_nacimiento = null,
         rtn = null, razon_social = null,
         anonimizado = true, activo = false
   where id_cliente = p_id_cliente;

  if not found then
    raise exception 'Cliente % no encontrado o sin permiso', p_id_cliente using errcode = 'P0002';
  end if;
end;
$$;

-- ---------------------------------------------------------------------
-- Promociones (estructura; el motor de reglas es del módulo de negocio)
-- ---------------------------------------------------------------------
create table public.promocion (
  id_promocion  bigint generated by default as identity primary key,
  nombre        varchar(80)   not null,
  tipo          varchar(15)   not null check (tipo in (
                  'PORC', 'MONTO', 'PRECIO', 'NxM', 'SEGUNDA_UNIDAD', 'COMBO', 'MONTO_COMPRA')),
  valor         numeric(12,2) check (valor >= 0),
  n_compra      int           check (n_compra > 0),
  m_paga        int           check (m_paga >= 0),
  inicio        timestamptz   not null,
  fin           timestamptz   not null,
  dias_semana   varchar(7),
  hora_inicio   time,
  hora_fin      time,
  solo_lealtad  boolean       not null default false,
  acumulable    boolean       not null default false,
  prioridad     int           not null default 0,
  activa        boolean       not null default true,
  check (fin > inicio),
  check (tipo <> 'PORC' or (valor > 0 and valor <= 100)),
  check (tipo <> 'NxM' or (n_compra is not null and m_paga is not null and m_paga < n_compra))
);
create index promocion_vigencia_idx on public.promocion (inicio, fin) where activa;

create table public.promocion_alcance (
  id_promocion   bigint      not null references public.promocion on delete cascade,
  tipo_objetivo  varchar(10) not null check (tipo_objetivo in ('PRODUCTO', 'CATEGORIA', 'SUCURSAL')),
  id_objetivo    bigint      not null,
  primary key (id_promocion, tipo_objetivo, id_objetivo)
);
