-- =====================================================================
-- 0900 · Caja, ventas, pagos, devoluciones y documentos (factura / ticket)
-- (doc 05 §2.3 y §3.3–3.6, doc 09 §9)
-- Estructura y reglas de integridad. El registro de una venta completa
-- (registrar_venta) lo implementa el módulo de negocio como UNA función
-- de Postgres, para que venta + líneas + pagos + kardex + correlativo
-- queden en la misma transacción (ver docs/contrato-equipo.md).
-- =====================================================================

create table public.forma_pago (
  id_forma_pago  bigint generated by default as identity primary key,
  clave          varchar(6)  not null unique check (clave in ('EFE', 'TDD', 'TDC', 'QR', 'VALE', 'PUNTOS')),
  nombre         varchar(40) not null,
  activa         boolean     not null default true
);

create table public.turno_caja (
  id_turno       bigint generated by default as identity primary key,
  id_caja        bigint        not null references public.caja,
  id_usuario     bigint        not null references public.usuario,
  apertura       timestamptz   not null default now(),
  cierre         timestamptz,
  fondo_inicial  numeric(12,2) not null check (fondo_inicial >= 0),
  estado         varchar(8)    not null default 'ABIERTO' check (estado in ('ABIERTO', 'CERRADO')),
  check ((estado = 'CERRADO') = (cierre is not null)),
  check (cierre is null or cierre >= apertura)
);
-- Doc 05 §3.6: solo un turno ABIERTO por caja a la vez.
create unique index turno_un_abierto_por_caja_idx on public.turno_caja (id_caja) where estado = 'ABIERTO';

create table public.movimiento_caja (
  id_mov_caja  bigint generated by default as identity primary key,
  id_turno     bigint        not null references public.turno_caja,
  tipo         varchar(8)    not null check (tipo in ('RETIRO', 'DEPOSITO', 'FONDO')),
  importe      numeric(12,2) not null check (importe > 0),
  motivo       varchar(200),
  id_usuario   bigint        not null references public.usuario,
  id_autoriza  bigint        references public.usuario,
  fecha        timestamptz   not null default now(),
  check (id_autoriza is null or id_autoriza <> id_usuario)
);
create index movimiento_caja_turno_idx on public.movimiento_caja (id_turno);

create table public.corte_caja (
  id_corte           bigint generated by default as identity primary key,
  id_turno           bigint        not null references public.turno_caja,
  tipo               char(1)       not null check (tipo in ('X', 'Z')),
  esperado_efectivo  numeric(12,2) not null,
  contado_efectivo   numeric(12,2) not null check (contado_efectivo >= 0),
  diferencia         numeric(12,2) generated always as (contado_efectivo - esperado_efectivo) stored,
  justificacion      varchar(250),
  id_supervisor      bigint        references public.usuario,
  fecha              timestamptz   not null default now(),
  -- Doc 05 §3.6: si hay diferencia, se exige justificación.
  check (contado_efectivo = esperado_efectivo or justificacion is not null)
);
create unique index corte_un_z_por_turno_idx on public.corte_caja (id_turno) where tipo = 'Z';

create table public.corte_denominacion (
  id_corte      bigint        not null references public.corte_caja on delete cascade,
  denominacion  numeric(8,2)  not null check (denominacion > 0),
  cantidad      int           not null check (cantidad >= 0),
  primary key (id_corte, denominacion)
);

create table public.venta (
  id_venta            uuid          primary key default gen_random_uuid(),   -- lo genera la caja
  folio               varchar(20)   not null unique,                         -- C03-000482
  id_turno            bigint        not null references public.turno_caja,
  id_caja             bigint        not null references public.caja,
  id_sucursal         bigint        not null references public.sucursal,     -- desnormalizado para reportes
  id_usuario          bigint        not null references public.usuario,      -- cajero
  id_cliente          bigint        references public.cliente,
  fecha               timestamptz   not null default now(),
  subtotal            numeric(12,2) not null check (subtotal >= 0),
  descuento           numeric(12,2) not null default 0 check (descuento >= 0),
  impuestos           numeric(12,2) not null default 0 check (impuestos >= 0),   -- ISV incluido en el total
  total               numeric(12,2) not null check (total >= 0),
  estado              varchar(10)   not null default 'ABIERTA' check (estado in (
                        'ABIERTA', 'SUSPENDIDA', 'PAGADA', 'CANCELADA', 'DEV_PARCIAL', 'DEV_TOTAL')),
  tipo_documento      varchar(12)   check (tipo_documento in ('TICKET', 'FACTURA_CF', 'FACTURA_RTN')),
  sincronizada        boolean       not null default true,
  id_autoriza_cancel  bigint        references public.usuario,
  motivo_cancelacion  varchar(250),
  -- Los precios incluyen ISV: total = subtotal - descuento (doc 05 §3.3).
  check (total = subtotal - descuento),
  check (estado not in ('PAGADA', 'DEV_PARCIAL', 'DEV_TOTAL') or tipo_documento is not null),
  check (estado <> 'CANCELADA' or (id_autoriza_cancel is not null and motivo_cancelacion is not null)),
  check (id_autoriza_cancel is null or id_autoriza_cancel <> id_usuario)    -- RN-ROL-01
);
create index venta_sucursal_fecha_idx on public.venta (id_sucursal, fecha);
create index venta_turno_idx on public.venta (id_turno);
create index venta_cliente_idx on public.venta (id_cliente) where id_cliente is not null;

create table public.venta_linea (
  id_venta              uuid          not null references public.venta on delete cascade,
  numero_linea          smallint      not null check (numero_linea > 0),
  id_producto           bigint        not null references public.producto,
  codigo_escaneado      varchar(20),
  cantidad              numeric(12,3) not null check (cantidad > 0),
  precio_unitario       numeric(12,2) not null check (precio_unitario >= 0),   -- congelado (RN-01)
  descuento             numeric(12,2) not null default 0 check (descuento >= 0),
  id_promocion          bigint        references public.promocion,
  clasificacion_fiscal  varchar(10)   not null references public.clasificacion_fiscal,  -- copiada al vender
  tasa_impuesto         numeric(5,4)  not null,
  importe               numeric(12,2) not null,
  costo_unitario        numeric(12,4) not null default 0,                     -- para margen
  cancelada             boolean       not null default false,
  primary key (id_venta, numero_linea),
  -- RN-03: el importe se redondea a 2 decimales.
  check (importe = round(cantidad * precio_unitario - descuento, 2)),
  check (descuento <= round(cantidad * precio_unitario, 2))
);
create index venta_linea_producto_idx on public.venta_linea (id_producto, id_venta);

create table public.pago (
  id_pago                bigint generated by default as identity primary key,
  id_venta               uuid          not null references public.venta on delete cascade,
  id_forma_pago          bigint        not null references public.forma_pago,
  importe                numeric(12,2) not null check (importe > 0),
  cambio                 numeric(12,2) not null default 0 check (cambio >= 0),
  autorizacion_bancaria  varchar(30),
  ultimos4               char(4)       check (ultimos4 ~ '^[0-9]{4}$'),     -- nunca el número completo
  check (cambio <= importe)
);
create index pago_venta_idx on public.pago (id_venta);

alter table public.movimiento_puntos
  add constraint movimiento_puntos_venta_fk foreign key (id_venta) references public.venta;

-- ---------------------------------------------------------------------
-- Documentos: factura SAR o ticket no fiscal (doc 09 §9)
-- ---------------------------------------------------------------------
create table public.documento_fiscal (
  id_documento         bigint generated by default as identity primary key,
  id_cai               bigint        not null references public.cai,
  correlativo          bigint        not null,
  numero               char(19)      not null unique check (numero ~ '^[0-9]{3}-[0-9]{3}-[0-9]{2}-[0-9]{8}$'),
  id_venta             uuid          references public.venta,
  id_documento_origen  bigint        references public.documento_fiscal,   -- notas de crédito
  fecha_emision        timestamptz   not null default now(),                -- RN-SAR-05: sin fecha manual
  id_cliente           bigint        references public.cliente,
  rtn_comprador        char(14)      check (rtn_comprador is null or public.rtn_valido(rtn_comprador)),
  nombre_comprador     varchar(150)  not null default 'CONSUMIDOR FINAL',
  orden_compra_exenta  varchar(40),
  constancia_exonerado varchar(40),
  registro_sag         varchar(40),
  importe_exonerado    numeric(12,2) not null default 0 check (importe_exonerado >= 0),
  importe_exento       numeric(12,2) not null default 0 check (importe_exento >= 0),
  importe_gravado_15   numeric(12,2) not null default 0 check (importe_gravado_15 >= 0),
  importe_gravado_18   numeric(12,2) not null default 0 check (importe_gravado_18 >= 0),
  isv_15               numeric(12,2) not null default 0 check (isv_15 >= 0),
  isv_18               numeric(12,2) not null default 0 check (isv_18 >= 0),
  total                numeric(12,2) not null check (total >= 0),
  total_letras         varchar(250)  not null,
  estado               varchar(8)    not null default 'VIGENTE' check (estado in ('VIGENTE', 'ANULADO')),
  motivo_anulacion     varchar(250),
  id_usuario_anula     bigint        references public.usuario,
  fecha_anulacion      timestamptz,
  pdf_url              text,
  reimpresiones        int           not null default 0 check (reimpresiones >= 0),
  -- RN-SAR-01: un correlativo nunca se reutiliza (vigente o anulado).
  unique (id_cai, correlativo),
  check (total = importe_exonerado + importe_exento + importe_gravado_15 + importe_gravado_18 + isv_15 + isv_18),
  check (estado <> 'ANULADO' or (motivo_anulacion is not null and id_usuario_anula is not null)),
  check (id_venta is not null or id_documento_origen is not null)
);
-- Una venta tiene a lo sumo una factura vigente (las notas de crédito aparte).
create unique index documento_una_factura_vigente_idx
  on public.documento_fiscal (id_venta)
  where estado = 'VIGENTE' and id_documento_origen is null;
create index documento_fecha_idx on public.documento_fiscal (fecha_emision);

-- La factura no se borra ni se le cambian montos o número; solo se anula.
create or replace function public.tg_documento_inmutable()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  if tg_op = 'DELETE' then
    raise exception 'Los documentos fiscales no se borran; se anulan' using hint = 'SOLO_INSERCION';
  end if;
  if (new.id_cai, new.correlativo, new.numero, new.id_venta, new.total, new.fecha_emision)
     is distinct from (old.id_cai, old.correlativo, old.numero, old.id_venta, old.total, old.fecha_emision) then
    raise exception 'Número, montos y fecha de un documento fiscal no se modifican' using hint = 'SOLO_INSERCION';
  end if;
  if old.estado = 'ANULADO' and new.estado = 'VIGENTE' then
    raise exception 'Un documento anulado no puede volver a estar vigente' using hint = 'SOLO_INSERCION';
  end if;
  return new;
end;
$$;

create trigger documento_inmutable
  before update or delete on public.documento_fiscal
  for each row execute function public.tg_documento_inmutable();

create table public.doc_fiscal_total (
  id_documento   bigint        not null references public.documento_fiscal on delete cascade,
  clasificacion  varchar(10)   not null check (clasificacion in ('EXENTO', 'EXONERADO', 'GRAVADO15', 'GRAVADO18')),
  base           numeric(12,2) not null check (base >= 0),
  impuesto       numeric(12,2) not null check (impuesto >= 0),
  primary key (id_documento, clasificacion)
);

create table public.ticket (
  id_ticket           bigint generated by default as identity primary key,
  numero              varchar(20) not null unique,                 -- T03-000482 (RN-DOC-02: sin formato fiscal)
  id_venta            uuid        not null unique references public.venta,
  codigo_canje        varchar(30) not null unique,
  fecha               timestamptz not null default now(),
  fecha_limite_canje  date        not null,
  estado              varchar(10) not null default 'EMITIDO' check (estado in ('EMITIDO', 'FACTURADO', 'VENCIDO')),
  id_documento_canje  bigint      unique references public.documento_fiscal,   -- RN-DOC-01: una sola vez
  check (numero !~ '^[0-9]{3}-[0-9]{3}-[0-9]{2}-'),
  check ((estado = 'FACTURADO') = (id_documento_canje is not null))
);

create table public.devolucion (
  id_devolucion    bigint generated by default as identity primary key,
  id_venta         uuid          not null references public.venta,
  fecha            timestamptz   not null default now(),
  motivo           varchar(250)  not null,
  forma_reembolso  varchar(6)    not null,
  total            numeric(12,2) not null check (total > 0),
  id_usuario       bigint        not null references public.usuario,
  id_autoriza      bigint        references public.usuario,
  id_nota_credito  bigint        references public.documento_fiscal,
  check (id_autoriza is null or id_autoriza <> id_usuario)
);

create table public.devolucion_linea (
  id_devolucion         bigint        not null references public.devolucion on delete cascade,
  numero_linea          smallint      not null,
  cantidad              numeric(12,3) not null check (cantidad > 0),
  reingresa_inventario  boolean       not null default true,
  primary key (id_devolucion, numero_linea)
);
